{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signal-engine-helm.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "signal-engine-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
