use std::collections::HashMap;
use std::sync::{Arc, RwLock};
use std::time::{SystemTime, UNIX_EPOCH};
use serde::{Serialize, Deserialize};
use crossbeam::channel::{bounded, Sender, Receiver};
use uuid::Uuid;

/// Trading signal generated by strategies
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub id: String,
    pub strategy_id: String,
    pub timestamp: u64,
    pub symbol: String,
    pub exchange: String,
    pub action: SignalAction,
    pub quantity: f64,
    pub price: Option<f64>,  // None for market orders
    pub confidence: f64,     // 0.0 to 1.0
    pub metadata: HashMap<String, String>,
}

/// Signal action types
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SignalAction {
    Buy,
    Sell,
    BuyLimit,
    SellLimit,
    Cancel,
    Hold,
    CancelAll,
}

/// Signal priority levels
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum SignalPriority {
    Low = 0,
    Normal = 1,
    High = 2,
    Critical = 3,
}

/// Signal status for tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SignalStatus {
    Pending,
    Submitted,
    PartiallyFilled(f64), // quantity filled
    Filled,
    Cancelled,
    Rejected(String), // reason
    Expired,
}

/// Extended signal information for tracking
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalInfo {
    pub signal: Signal,
    pub priority: SignalPriority,
    pub status: SignalStatus,
    pub created_at: u64,
    pub updated_at: u64,
    pub execution_price: Option<f64>,
    pub executed_quantity: Option<f64>,
    pub fees: Option<f64>,
}

impl Signal {
    /// Create a new signal
    pub fn new(
        strategy_id: String,
        symbol: String,
        exchange: String,
        action: SignalAction,
        quantity: f64,
        price: Option<f64>,
        confidence: f64,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            strategy_id,
            timestamp: SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_millis() as u64,
            symbol,
            exchange,
            action,
            quantity,
            price,
            confidence,
            metadata: HashMap::new(),
        }
    }

    /// Add metadata to signal
    pub fn with_metadata(mut self, key: String, value: String) -> Self {
        self.metadata.insert(key, value);
        self
    }

    /// Create a cancel all signal
    pub fn cancel_all(strategy_id: String, symbol: String, exchange: String) -> Self {
        Self::new(
            strategy_id,
            symbol,
            exchange,
            SignalAction::CancelAll,
            0.0,
            None,
            1.0,
        )
    }

    /// Create a buy limit signal
    pub fn buy_limit(
        strategy_id: String,
        symbol: String,
        exchange: String,
        quantity: f64,
        price: f64,
        confidence: f64,
    ) -> Self {
        Self::new(
            strategy_id,
            symbol,
            exchange,
            SignalAction::BuyLimit,
            quantity,
            Some(price),
            confidence,
        )
    }

    /// Create a sell limit signal
    pub fn sell_limit(
        strategy_id: String,
        symbol: String,
        exchange: String,
        quantity: f64,
        price: f64,
        confidence: f64,
    ) -> Self {
        Self::new(
            strategy_id,
            symbol,
            exchange,
            SignalAction::SellLimit,
            quantity,
            Some(price),
            confidence,
        )
    }

    /// Determine signal priority based on action and confidence
    pub fn priority(&self) -> SignalPriority {
        match self.action {
            SignalAction::CancelAll | SignalAction::Cancel => SignalPriority::Critical,
            _ => {
                if self.confidence >= 0.9 {
                    SignalPriority::High
                } else if self.confidence >= 0.7 {
                    SignalPriority::Normal
                } else {
                    SignalPriority::Low
                }
            }
        }
    }

    /// Check if signal is valid
    pub fn is_valid(&self) -> Result<(), String> {
        // Validate quantity
        if self.quantity < 0.0 {
            return Err("Quantity cannot be negative".to_string());
        }

        // Validate price for limit orders
        match self.action {
            SignalAction::BuyLimit | SignalAction::SellLimit => {
                if self.price.is_none() || self.price.unwrap() <= 0.0 {
                    return Err("Limit orders must have a positive price".to_string());
                }
            }
            _ => {}
        }

        // Validate confidence
        if self.confidence < 0.0 || self.confidence > 1.0 {
            return Err("Confidence must be between 0.0 and 1.0".to_string());
        }

        Ok(())
    }
}

impl SignalInfo {
    /// Create new signal info
    pub fn new(signal: Signal) -> Self {
        let now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_millis() as u64;
        Self {
            priority: signal.priority(),
            signal,
            status: SignalStatus::Pending,
            created_at: now,
            updated_at: now,
            execution_price: None,
            executed_quantity: None,
            fees: None,
        }
    }

    /// Update status
    pub fn update_status(&mut self, status: SignalStatus) {
        self.status = status;
        self.updated_at = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_millis() as u64;
    }

    /// Record execution
    pub fn record_execution(&mut self, price: f64, quantity: f64, fees: f64) {
        self.execution_price = Some(price);
        self.executed_quantity = Some(quantity);
        self.fees = Some(fees);
        self.status = if quantity >= self.signal.quantity * 0.99 {
            SignalStatus::Filled
        } else {
            SignalStatus::PartiallyFilled(quantity)
        };
        self.updated_at = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_millis() as u64;
    }

    /// Calculate PnL if executed
    pub fn calculate_pnl(&self) -> Option<f64> {
        if let (Some(exec_price), Some(exec_qty), Some(signal_price)) = 
            (self.execution_price, self.executed_quantity, self.signal.price) {
            let gross_pnl = match self.signal.action {
                SignalAction::Buy | SignalAction::BuyLimit => (exec_price - signal_price) * exec_qty,
                SignalAction::Sell | SignalAction::SellLimit => (signal_price - exec_price) * exec_qty,
                _ => 0.0,
            };
            Some(gross_pnl - self.fees.unwrap_or(0.0))
        } else {
            None
        }
    }
}

/// Signal aggregator for combining signals from multiple sources
pub struct SignalAggregator {
    receivers: Vec<Receiver<Signal>>,
    sender: Sender<Signal>,
    receiver: Receiver<Signal>,
}

impl SignalAggregator {
    /// Create new signal aggregator
    pub fn new(buffer_size: usize) -> Self {
        let (sender, receiver) = bounded(buffer_size);
        Self {
            receivers: Vec::new(),
            sender,
            receiver,
        }
    }

    /// Add a signal source
    pub fn add_source(&mut self, receiver: Receiver<Signal>) {
        self.receivers.push(receiver);
    }

    /// Get aggregated receiver
    pub fn receiver(&self) -> Receiver<Signal> {
        self.receiver.clone()
    }

    /// Run aggregation (should be called in a separate thread)
    pub fn run(&self) {
        loop {
            for receiver in &self.receivers {
                // Try to receive from each source
                if let Ok(signal) = receiver.try_recv() {
                    if let Err(e) = self.sender.try_send(signal) {
                        eprintln!("Failed to send aggregated signal: {}", e);
                    }
                }
            }
            std::thread::sleep(std::time::Duration::from_micros(100));
        }
    }
}

/// Signal filter for filtering signals based on criteria
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalFilter {
    min_confidence: f64,
    allowed_actions: Vec<SignalAction>,
    allowed_symbols: Vec<String>,
    allowed_exchanges: Vec<String>,
    max_order_size: Option<f64>,
}

impl SignalFilter {
    /// Create new signal filter
    pub fn new() -> Self {
        Self {
            min_confidence: 0.0,
            allowed_actions: vec![
                SignalAction::Buy,
                SignalAction::Sell,
                SignalAction::BuyLimit,
                SignalAction::SellLimit,
                SignalAction::Cancel,
                SignalAction::CancelAll,
            ],
            allowed_symbols: Vec::new(),
            allowed_exchanges: Vec::new(),
            max_order_size: None,
        }
    }

    /// Set minimum confidence
    pub fn with_min_confidence(mut self, confidence: f64) -> Self {
        self.min_confidence = confidence;
        self
    }

    /// Set allowed actions
    pub fn with_allowed_actions(mut self, actions: Vec<SignalAction>) -> Self {
        self.allowed_actions = actions;
        self
    }

    /// Set allowed symbols (empty = all allowed)
    pub fn with_allowed_symbols(mut self, symbols: Vec<String>) -> Self {
        self.allowed_symbols = symbols;
        self
    }

    /// Set allowed exchanges (empty = all allowed)
    pub fn with_allowed_exchanges(mut self, exchanges: Vec<String>) -> Self {
        self.allowed_exchanges = exchanges;
        self
    }

    /// Set maximum order size
    pub fn with_max_order_size(mut self, size: f64) -> Self {
        self.max_order_size = Some(size);
        self
    }

    /// Check if signal passes filter
    pub fn passes(&self, signal: &Signal) -> bool {
        // Check confidence
        if signal.confidence < self.min_confidence {
            return false;
        }

        // Check action
        if !self.allowed_actions.contains(&signal.action) {
            return false;
        }

        // Check symbol
        if !self.allowed_symbols.is_empty() && !self.allowed_symbols.contains(&signal.symbol) {
            return false;
        }

        // Check exchange
        if !self.allowed_exchanges.is_empty() && !self.allowed_exchanges.contains(&signal.exchange) {
            return false;
        }

        // Check order size
        if let Some(max_size) = self.max_order_size {
            if signal.quantity > max_size {
                return false;
            }
        }

        true
    }
}

/// Signal router for routing signals to different handlers
pub struct SignalRouter {
    routes: HashMap<String, Vec<Sender<Signal>>>, // strategy_id -> handlers
    default_handlers: Vec<Sender<Signal>>,
}

impl SignalRouter {
    /// Create new signal router
    pub fn new() -> Self {
        Self {
            routes: HashMap::new(),
            default_handlers: Vec::new(),
        }
    }

    /// Add route for specific strategy
    pub fn add_route(&mut self, strategy_id: String, handler: Sender<Signal>) {
        self.routes.entry(strategy_id).or_insert_with(Vec::new).push(handler);
    }

    /// Add default handler (receives all signals)
    pub fn add_default_handler(&mut self, handler: Sender<Signal>) {
        self.default_handlers.push(handler);
    }

    /// Route a signal
    pub fn route(&self, signal: Signal) -> Result<(), String> {
        let mut sent = false;

        // Send to strategy-specific handlers
        if let Some(handlers) = self.routes.get(&signal.strategy_id) {
            for handler in handlers {
                if let Err(e) = handler.try_send(signal.clone()) {
                    eprintln!("Failed to route signal to strategy handler: {}", e);
                } else {
                    sent = true;
                }
            }
        }

        // Send to default handlers
        for handler in &self.default_handlers {
            if let Err(e) = handler.try_send(signal.clone()) {
                eprintln!("Failed to route signal to default handler: {}", e);
            } else {
                sent = true;
            }
        }

        if sent {
            Ok(())
        } else {
            Err("No handlers available for signal".to_string())
        }
    }
}

/// Signal store for persisting signals
pub struct SignalStore {
    signals: Arc<RwLock<HashMap<String, SignalInfo>>>,
    by_strategy: Arc<RwLock<HashMap<String, Vec<String>>>>, // strategy_id -> signal_ids
    by_symbol: Arc<RwLock<HashMap<String, Vec<String>>>>,   // symbol -> signal_ids
}

impl SignalStore {
    /// Create new signal store
    pub fn new() -> Self {
        Self {
            signals: Arc::new(RwLock::new(HashMap::new())),
            by_strategy: Arc::new(RwLock::new(HashMap::new())),
            by_symbol: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    /// Store a signal
    pub fn store(&self, signal: Signal) -> Result<(), String> {
        let signal_id = signal.id.clone();
        let strategy_id = signal.strategy_id.clone();
        let symbol = signal.symbol.clone();
        
        let signal_info = SignalInfo::new(signal);

        // Store signal
        {
            let mut signals = self.signals.write().unwrap();
            signals.insert(signal_id.clone(), signal_info);
        }

        // Update indices
        {
            let mut by_strategy = self.by_strategy.write().unwrap();
            by_strategy.entry(strategy_id).or_insert_with(Vec::new).push(signal_id.clone());
        }

        {
            let mut by_symbol = self.by_symbol.write().unwrap();
            by_symbol.entry(symbol).or_insert_with(Vec::new).push(signal_id.clone());
        }

        Ok(())
    }

    /// Get signal by ID
    pub fn get(&self, signal_id: &str) -> Option<SignalInfo> {
        let signals = self.signals.read().unwrap();
        signals.get(signal_id).cloned()
    }

    /// Get signals by strategy
    pub fn get_by_strategy(&self, strategy_id: &str) -> Vec<SignalInfo> {
        let by_strategy = self.by_strategy.read().unwrap();
        let signals = self.signals.read().unwrap();
        
        if let Some(signal_ids) = by_strategy.get(strategy_id) {
            signal_ids.iter()
                .filter_map(|id| signals.get(id).cloned())
                .collect()
        } else {
            Vec::new()
        }
    }

    /// Get signals by symbol
    pub fn get_by_symbol(&self, symbol: &str) -> Vec<SignalInfo> {
        let by_symbol = self.by_symbol.read().unwrap();
        let signals = self.signals.read().unwrap();
        
        if let Some(signal_ids) = by_symbol.get(symbol) {
            signal_ids.iter()
                .filter_map(|id| signals.get(id).cloned())
                .collect()
        } else {
            Vec::new()
        }
    }

    /// Update signal status
    pub fn update_status(&self, signal_id: &str, status: SignalStatus) -> Result<(), String> {
        let mut signals = self.signals.write().unwrap();
        
        if let Some(signal_info) = signals.get_mut(signal_id) {
            signal_info.update_status(status);
            Ok(())
        } else {
            Err(format!("Signal {} not found", signal_id))
        }
    }

    /// Record execution
    pub fn record_execution(
        &self,
        signal_id: &str,
        price: f64,
        quantity: f64,
        fees: f64,
    ) -> Result<(), String> {
        let mut signals = self.signals.write().unwrap();
        
        if let Some(signal_info) = signals.get_mut(signal_id) {
            signal_info.record_execution(price, quantity, fees);
            Ok(())
        } else {
            Err(format!("Signal {} not found", signal_id))
        }
    }

    /// Get performance statistics
    pub fn get_stats(&self) -> SignalStats {
        let signals = self.signals.read().unwrap();
        
        let mut stats = SignalStats::default();
        stats.total_signals = signals.len();
        
        for signal_info in signals.values() {
            match &signal_info.status {
                SignalStatus::Pending => stats.pending_signals += 1,
                SignalStatus::Submitted => stats.submitted_signals += 1,
                SignalStatus::Filled => {
                    stats.filled_signals += 1;
                    if let Some(pnl) = signal_info.calculate_pnl() {
                        stats.total_pnl += pnl;
                        if pnl > 0.0 {
                            stats.profitable_signals += 1;
                        }
                    }
                }
                SignalStatus::PartiallyFilled(_) => stats.partial_signals += 1,
                SignalStatus::Cancelled => stats.cancelled_signals += 1,
                SignalStatus::Rejected(_) => stats.rejected_signals += 1,
                SignalStatus::Expired => stats.expired_signals += 1,
            }
        }
        
        if stats.filled_signals > 0 {
            stats.win_rate = stats.profitable_signals as f64 / stats.filled_signals as f64;
        }
        
        stats
    }
}

/// Signal statistics
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SignalStats {
    pub total_signals: usize,
    pub pending_signals: usize,
    pub submitted_signals: usize,
    pub filled_signals: usize,
    pub partial_signals: usize,
    pub cancelled_signals: usize,
    pub rejected_signals: usize,
    pub expired_signals: usize,
    pub profitable_signals: usize,
    pub total_pnl: f64,
    pub win_rate: f64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_signal_creation() {
        let signal = Signal::buy_limit(
            "strategy1".to_string(),
            "BTC/USD".to_string(),
            "binance".to_string(),
            1.0,
            50000.0,
            0.85,
        );

        assert_eq!(signal.strategy_id, "strategy1");
        assert_eq!(signal.action, SignalAction::BuyLimit);
        assert_eq!(signal.quantity, 1.0);
        assert_eq!(signal.price, Some(50000.0));
        assert_eq!(signal.confidence, 0.85);
        assert!(signal.is_valid().is_ok());
    }

    #[test]
    fn test_signal_priority() {
        let cancel_signal = Signal::cancel_all("s1".to_string(), "ETH/USD".to_string(), "coinbase".to_string());
        assert_eq!(cancel_signal.priority(), SignalPriority::Critical);

        let high_conf_signal = Signal::buy_limit("s1".to_string(), "ETH/USD".to_string(), "coinbase".to_string(), 1.0, 3000.0, 0.95);
        assert_eq!(high_conf_signal.priority(), SignalPriority::High);

        let low_conf_signal = Signal::sell_limit("s1".to_string(), "ETH/USD".to_string(), "coinbase".to_string(), 1.0, 3000.0, 0.5);
        assert_eq!(low_conf_signal.priority(), SignalPriority::Low);
    }

    #[test]
    fn test_signal_filter() {
        let filter = SignalFilter::new()
            .with_min_confidence(0.7)
            .with_allowed_symbols(vec!["BTC/USD".to_string(), "ETH/USD".to_string()])
            .with_max_order_size(10.0);

        let good_signal = Signal::buy_limit("s1".to_string(), "BTC/USD".to_string(), "binance".to_string(), 5.0, 50000.0, 0.8);
        assert!(filter.passes(&good_signal));

        let low_conf_signal = Signal::buy_limit("s1".to_string(), "BTC/USD".to_string(), "binance".to_string(), 5.0, 50000.0, 0.5);
        assert!(!filter.passes(&low_conf_signal));

        let wrong_symbol_signal = Signal::buy_limit("s1".to_string(), "DOGE/USD".to_string(), "binance".to_string(), 5.0, 1.0, 0.8);
        assert!(!filter.passes(&wrong_symbol_signal));

        let large_order_signal = Signal::buy_limit("s1".to_string(), "BTC/USD".to_string(), "binance".to_string(), 15.0, 50000.0, 0.8);
        assert!(!filter.passes(&large_order_signal));
    }

    #[test]
    fn test_signal_store() {
        let store = SignalStore::new();
        
        let signal1 = Signal::buy_limit("strategy1".to_string(), "BTC/USD".to_string(), "binance".to_string(), 1.0, 50000.0, 0.8);
        let signal1_id = signal1.id.clone();
        
        // Store signal
        store.store(signal1).unwrap();
        
        // Retrieve by ID
        let retrieved = store.get(&signal1_id).unwrap();
        assert_eq!(retrieved.signal.id, signal1_id);
        assert_eq!(retrieved.status, SignalStatus::Pending);
        
        // Update status
        store.update_status(&signal1_id, SignalStatus::Submitted).unwrap();
        let updated = store.get(&signal1_id).unwrap();
        assert_eq!(updated.status, SignalStatus::Submitted);
        
        // Record execution
        store.record_execution(&signal1_id, 49950.0, 1.0, 25.0).unwrap();
        let executed = store.get(&signal1_id).unwrap();
        assert_eq!(executed.status, SignalStatus::Filled);
        assert_eq!(executed.execution_price, Some(49950.0));
        
        // Check PnL calculation (bought at 50000, executed at 49950, so -50 - 25 fees = -75)
        let pnl = executed.calculate_pnl().unwrap();
        assert_eq!(pnl, -75.0);
        
        // Check stats
        let stats = store.get_stats();
        assert_eq!(stats.total_signals, 1);
        assert_eq!(stats.filled_signals, 1);
        assert_eq!(stats.total_pnl, -75.0);
    }
}