[package]
name = "smartorderrouter"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
exchangemetricaggregator = { path = "../exchangemetricaggregator" }
databaseschema = { path = "../../databaseschema" }
deadpool = "0.10"
bigdecimal = "0.4"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
