[package]
name = "strategyhandler"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
bigdecimal = "0.4.8"
chrono = "0.4.41"
crossbeam = "0.8.4"
lazy_static = "1.5.0"
orderbook = { path = "../orderbook" }
portfolio = { path = "../portfolio" }
serde = "1.0.219"
serde_json = "1.0.140"
strategy = { path = "../../BacktestingEngine/strategy" }
tokio = "1.45.1"
uuid = "1.17.0"
