//! Strategy execution traits and implementations
//!
//! Defines the PortfolioStrategy trait that all strategies implement,
//! enabling parameterized execution based on loaded configuration.

use std::sync::Arc;
use uuid::Uuid;
use ultra_logger::ultra_warn;
use crate::types::{
    StrategyInstance, StrategyParameters, MomentumParams, MeanReversionParams,
    DataRequirements, ExecutionStyle, data_requirements_for_strategy_type,
    execution_style_for_strategy_type,
};
use crate::state::{StrategyState, AssetState};

/// Signal generated by a strategy
#[derive(Debug, Clone)]
pub struct Signal {
    /// Strategy that generated this signal
    pub strategy_id: Uuid,
    
    /// Symbol to trade
    pub symbol: String,
    
    /// Exchange to execute on
    pub exchange: String,
    
    /// Signal direction and magnitude (-1.0 to 1.0)
    /// Positive = buy/long, Negative = sell/short
    /// Magnitude indicates confidence/size
    pub direction: f64,
    
    /// Optional target price
    pub target_price: Option<f64>,
    
    /// Optional stop loss price
    pub stop_loss: Option<f64>,
    
    /// Signal confidence (0.0 to 1.0)
    pub confidence: f64,
    
    /// Reason for signal generation
    pub reason: String,
    
    /// Timestamp (ms)
    pub timestamp_ms: i64,
}

impl Signal {
    /// Create a buy signal
    pub fn buy(
        strategy_id: Uuid,
        symbol: String,
        exchange: String,
        magnitude: f64,
        confidence: f64,
        reason: String,
        timestamp_ms: i64,
    ) -> Self {
        Self {
            strategy_id,
            symbol,
            exchange,
            direction: magnitude.abs().min(1.0),
            target_price: None,
            stop_loss: None,
            confidence,
            reason,
            timestamp_ms,
        }
    }
    
    /// Create a sell signal
    pub fn sell(
        strategy_id: Uuid,
        symbol: String,
        exchange: String,
        magnitude: f64,
        confidence: f64,
        reason: String,
        timestamp_ms: i64,
    ) -> Self {
        Self {
            strategy_id,
            symbol,
            exchange,
            direction: -magnitude.abs().min(1.0),
            target_price: None,
            stop_loss: None,
            confidence,
            reason,
            timestamp_ms,
        }
    }
    
    /// Create a close position signal
    pub fn close(
        strategy_id: Uuid,
        symbol: String,
        exchange: String,
        reason: String,
        timestamp_ms: i64,
    ) -> Self {
        Self {
            strategy_id,
            symbol,
            exchange,
            direction: 0.0, // Zero means close current position
            target_price: None,
            stop_loss: None,
            confidence: 1.0,
            reason,
            timestamp_ms,
        }
    }
    
    pub fn is_buy(&self) -> bool {
        self.direction > 0.0
    }
    
    pub fn is_sell(&self) -> bool {
        self.direction < 0.0
    }
    
    pub fn is_close(&self) -> bool {
        self.direction == 0.0
    }
    
    pub fn with_target(mut self, price: f64) -> Self {
        self.target_price = Some(price);
        self
    }
    
    pub fn with_stop_loss(mut self, price: f64) -> Self {
        self.stop_loss = Some(price);
        self
    }
}

/// Market data event for strategy processing
#[derive(Debug, Clone)]
pub struct MarketDataEvent {
    pub symbol: String,
    pub exchange: String,
    pub timestamp_ms: i64,
    pub price: f64,
    pub volume: Option<f64>,
    pub bid: Option<f64>,
    pub ask: Option<f64>,
}

/// Trait for strategy execution
/// 
/// Strategies implement this trait to process market data and generate signals.
/// Each strategy is parameterized by its StrategyInstance configuration.
pub trait PortfolioStrategy: Send + Sync {
    /// Get strategy ID
    fn strategy_id(&self) -> Uuid;
    
    /// Get strategy name
    fn name(&self) -> &str;
    
    /// Process a market data event and potentially generate signals
    fn on_market_data(
        &self,
        event: &MarketDataEvent,
        state: &mut StrategyState,
    ) -> Vec<Signal>;
    
    /// Called when an order is filled
    fn on_fill(
        &self,
        symbol: &str,
        exchange: &str,
        quantity: f64,
        price: f64,
        is_buy: bool,
        state: &mut StrategyState,
    ) {
        if let Some(asset) = state.get_asset_mut(symbol, exchange) {
            asset.record_trade(quantity, price, is_buy);
        }
    }
    
    /// Check if strategy should be in cooldown
    fn check_risk_limits(&self, state: &mut StrategyState) -> bool {
        if state.is_daily_loss_exceeded() {
            state.enter_cooldown("Daily loss limit exceeded");
            return true;
        }
        if state.is_max_drawdown_exceeded() {
            state.enter_cooldown("Max drawdown exceeded");
            return true;
        }
        false
    }

    /// Market data this strategy needs to function correctly.
    ///
    /// Default implementation derives the answer from the strategy
    /// instance's `strategy_type` label so legacy implementations don't
    /// need to be migrated. Strategies that want fine-grained control
    /// (e.g. a custom Python strategy declaring orderbook needs in its
    /// metadata JSON) should override this method.
    ///
    /// Used by the deployment subscriber to decide whether to subscribe
    /// to L3 orderbook data, replacing the brittle
    /// `strategy_type == "custom_market_making"` literal that previously
    /// guarded that decision.
    fn data_requirements(&self) -> DataRequirements {
        data_requirements_for_strategy_type(&self.strategy_type_label())
    }

    /// How this strategy interacts with the order book. Defaults to
    /// `Aggressive` for directional strategies; market makers should
    /// override (or rely on the default that keys off `strategy_type`).
    fn execution_style(&self) -> ExecutionStyle {
        execution_style_for_strategy_type(&self.strategy_type_label())
    }

    /// String label used by the default capability implementations.
    /// Defaults to `"custom"` so unmigrated strategies still compile.
    /// Override when a strategy knows its own type (e.g. wraps a
    /// `StrategyInstance` and can return `instance.strategy_type.to_string()`).
    fn strategy_type_label(&self) -> String {
        "custom".to_string()
    }
}

/// Momentum strategy executor
pub struct MomentumStrategy {
    instance: StrategyInstance,
    params: MomentumParams,
}

impl MomentumStrategy {
    /// Create from strategy instance
    pub fn new(instance: StrategyInstance) -> Option<Self> {
        let params = match &instance.parameters {
            StrategyParameters::Momentum(p) => p.clone(),
            _ => return None,
        };
        
        Some(Self { instance, params })
    }
}

impl PortfolioStrategy for MomentumStrategy {
    fn strategy_id(&self) -> Uuid {
        self.instance.id
    }
    
    fn name(&self) -> &str {
        &self.instance.name
    }
    
    fn on_market_data(
        &self,
        event: &MarketDataEvent,
        state: &mut StrategyState,
    ) -> Vec<Signal> {
        let mut signals = Vec::new();
        
        // Check cooldown
        state.check_cooldown();
        if state.in_cooldown {
            return signals;
        }
        
        // Check risk limits
        if self.check_risk_limits(state) {
            return signals;
        }
        
        // Get asset state
        let Some(asset) = state.get_asset_mut(&event.symbol, &event.exchange) else {
            return signals;
        };
        
        // Update price
        asset.update_price(event.timestamp_ms, event.price);
        
        // Need enough history for momentum calculation
        let lookback_ms = self.params.momentum_lookback_ms;
        let Some(momentum) = asset.calculate_momentum(lookback_ms) else {
            return signals;
        };
        
        // Apply momentum threshold
        let threshold = self.params.momentum_threshold_pct;
        let exit_threshold = threshold * 0.5; // Exit at half the entry threshold
        
        // Current position check
        let has_position = !asset.is_flat();
        
        if momentum > threshold && !asset.is_long() {
            // Strong upward momentum - buy signal
            let confidence = ((momentum - threshold) / threshold).min(1.0);
            let signal = Signal::buy(
                self.instance.id,
                event.symbol.clone(),
                event.exchange.clone(),
                1.0,
                confidence,
                format!("Momentum {:.2}% > {:.2}% threshold", momentum, threshold),
                event.timestamp_ms,
            );
            signals.push(signal);
            
        } else if momentum < -threshold && !asset.is_short() {
            // Strong downward momentum - sell signal
            let confidence = ((-momentum - threshold) / threshold).min(1.0);
            let signal = Signal::sell(
                self.instance.id,
                event.symbol.clone(),
                event.exchange.clone(),
                1.0,
                confidence,
                format!("Momentum {:.2}% < -{:.2}% threshold", momentum, threshold),
                event.timestamp_ms,
            );
            signals.push(signal);
            
        } else if has_position {
            // Check for exit signals
            if asset.is_long() && momentum < -exit_threshold {
                let signal = Signal::close(
                    self.instance.id,
                    event.symbol.clone(),
                    event.exchange.clone(),
                    format!("Momentum reversal {:.2}% < -{:.2}%", momentum, exit_threshold),
                    event.timestamp_ms,
                );
                signals.push(signal);
                
            } else if asset.is_short() && momentum > exit_threshold {
                let signal = Signal::close(
                    self.instance.id,
                    event.symbol.clone(),
                    event.exchange.clone(),
                    format!("Momentum reversal {:.2}% > {:.2}%", momentum, exit_threshold),
                    event.timestamp_ms,
                );
                signals.push(signal);
            }
        }
        
        signals
    }
}

/// Mean reversion strategy executor  
pub struct MeanReversionStrategy {
    instance: StrategyInstance,
    params: MeanReversionParams,
}

impl MeanReversionStrategy {
    /// Create from strategy instance
    pub fn new(instance: StrategyInstance) -> Option<Self> {
        let params = match &instance.parameters {
            StrategyParameters::MeanReversion(p) => p.clone(),
            _ => return None,
        };
        
        Some(Self { instance, params })
    }
    
    /// Calculate z-score from price history
    fn calculate_zscore(&self, asset: &AssetState) -> Option<f64> {
        // Convert lookback_ms to approximate number of data points
        // Assuming ~1 update per second, divide by 1000
        let lookback_count = (self.params.lookback_ms / 1000).max(10) as usize;
        
        let prices: Vec<f64> = asset.price_history.iter()
            .rev()
            .take(lookback_count)
            .map(|(_, p)| *p)
            .collect();
        
        if prices.len() < lookback_count {
            return None;
        }
        
        let mean: f64 = prices.iter().sum::<f64>() / prices.len() as f64;
        let variance: f64 = prices.iter()
            .map(|p| (p - mean).powi(2))
            .sum::<f64>() / prices.len() as f64;
        let std_dev = variance.sqrt();
        
        if std_dev > 0.0 {
            Some((asset.current_price - mean) / std_dev)
        } else {
            None
        }
    }
}

impl PortfolioStrategy for MeanReversionStrategy {
    fn strategy_id(&self) -> Uuid {
        self.instance.id
    }
    
    fn name(&self) -> &str {
        &self.instance.name
    }
    
    fn on_market_data(
        &self,
        event: &MarketDataEvent,
        state: &mut StrategyState,
    ) -> Vec<Signal> {
        let mut signals = Vec::new();
        
        // Check cooldown
        state.check_cooldown();
        if state.in_cooldown {
            return signals;
        }
        
        // Check risk limits
        if self.check_risk_limits(state) {
            return signals;
        }
        
        // Get asset state
        let Some(asset) = state.get_asset_mut(&event.symbol, &event.exchange) else {
            return signals;
        };
        
        // Update price
        asset.update_price(event.timestamp_ms, event.price);
        
        // Calculate z-score
        let Some(zscore) = self.calculate_zscore(asset) else {
            return signals;
        };
        
        let entry_threshold = self.params.zscore_entry_threshold;
        let exit_threshold = self.params.zscore_exit_threshold;
        
        if zscore < -entry_threshold && !asset.is_long() {
            // Price significantly below mean - buy
            let confidence = ((-zscore - entry_threshold) / entry_threshold).min(1.0);
            let signal = Signal::buy(
                self.instance.id,
                event.symbol.clone(),
                event.exchange.clone(),
                1.0,
                confidence,
                format!("Z-score {:.2} < -{:.2} (mean reversion buy)", zscore, entry_threshold),
                event.timestamp_ms,
            );
            signals.push(signal);
            
        } else if zscore > entry_threshold && !asset.is_short() {
            // Price significantly above mean - sell
            let confidence = ((zscore - entry_threshold) / entry_threshold).min(1.0);
            let signal = Signal::sell(
                self.instance.id,
                event.symbol.clone(),
                event.exchange.clone(),
                1.0,
                confidence,
                format!("Z-score {:.2} > {:.2} (mean reversion sell)", zscore, entry_threshold),
                event.timestamp_ms,
            );
            signals.push(signal);
            
        } else if asset.is_long() && zscore > -exit_threshold {
            // Long position, price reverted to mean - close
            let signal = Signal::close(
                self.instance.id,
                event.symbol.clone(),
                event.exchange.clone(),
                format!("Z-score {:.2} > -{:.2} (mean reversion target)", zscore, exit_threshold),
                event.timestamp_ms,
            );
            signals.push(signal);
            
        } else if asset.is_short() && zscore < exit_threshold {
            // Short position, price reverted to mean - close
            let signal = Signal::close(
                self.instance.id,
                event.symbol.clone(),
                event.exchange.clone(),
                format!("Z-score {:.2} < {:.2} (mean reversion target)", zscore, exit_threshold),
                event.timestamp_ms,
            );
            signals.push(signal);
        }
        
        signals
    }
}

/// Factory for creating strategy executors from instances
pub struct StrategyFactory;

impl StrategyFactory {
    /// Create appropriate strategy executor from instance
    pub fn create(instance: StrategyInstance) -> Option<Arc<dyn PortfolioStrategy>> {
        match &instance.parameters {
            StrategyParameters::Momentum(_) => {
                MomentumStrategy::new(instance).map(|s| Arc::new(s) as Arc<dyn PortfolioStrategy>)
            }
            StrategyParameters::MeanReversion(_) => {
                MeanReversionStrategy::new(instance).map(|s| Arc::new(s) as Arc<dyn PortfolioStrategy>)
            }
            StrategyParameters::Generic(_) => {
                ultra_warn!("Generic strategy requires custom implementation");
                None
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{TradingAsset, PortfolioRiskLimits, AssetRiskLimits, StrategyType};
    
    fn create_test_momentum_instance() -> StrategyInstance {
        StrategyInstance {
            id: Uuid::new_v4(),
            name: "Test Custom".into(),
            strategy_type: StrategyType::Custom,
            version: "1.0.0".into(),
            parameters: StrategyParameters::Momentum(MomentumParams {
                momentum_threshold_pct: 0.5,
                momentum_lookback_ms: 60_000,
                imbalance_threshold: 0.3,
                position_size_pct: 0.10,
                take_profit_pct: 0.8,
                stop_loss_pct: 0.5,
                min_trade_interval_ms: 1000,
                use_volume_confirmation: false,
                volume_multiplier: 1.5,
            }),
            assets: vec![TradingAsset {
                symbol: "BTC/USD".into(),
                exchange: "kraken".into(),
                weight: 1.0,
                risk_limits: AssetRiskLimits::default(),
            }],
            portfolio_risk: PortfolioRiskLimits::default(),
            enabled: true,
            description: None,
            python_source: None,
            metadata: Default::default(),
        }
    }
    
    #[test]
    fn test_momentum_strategy_creation() {
        let instance = create_test_momentum_instance();
        let strategy = MomentumStrategy::new(instance);
        assert!(strategy.is_some());
    }
    
    #[test]
    fn test_signal_creation() {
        let signal = Signal::buy(
            Uuid::new_v4(),
            "BTC/USD".into(),
            "kraken".into(),
            1.0,
            0.8,
            "Test".into(),
            1000,
        );
        
        assert!(signal.is_buy());
        assert!(!signal.is_sell());
        assert_eq!(signal.confidence, 0.8);
    }
    
    #[test]
    fn test_factory() {
        let instance = create_test_momentum_instance();
        let strategy = StrategyFactory::create(instance);
        assert!(strategy.is_some());
    }
}
