[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
hostbuilder = { path = "../crates/hostbuilder" }
signalengine = { package = "signalengine-core", path = "../crates/core" }
tokio = "1.44.1"
# Ultra-low latency logging
ultra-logger = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
