//! Long-only equivalence: the planner's output for long-only sleeves must stay byte for byte what it was before the
//! signed-weights extension (default OFF) was added.
//!
//! `tests/golden/long_only_plans.txt` was generated by running THIS test with `GOLDEN_UPDATE=1` against the
//! UNMODIFIED planner (commit `6a312b0`, before any signed-weight code existed) and committed on its own before the
//! extension. Each line is the SHA-256 of a canonical text of one plan (or of the error it returned), for a seeded
//! random case that mixes valid and invalid inputs: held shorts, negative or oversized weights, sums above 1, bad risk
//! scales, stale or missing prices, halted accounts, tight and loose mandates. Only fields that existed at that commit
//! are read, so adding new fields to the plan types does not disturb the check; only a change in behaviour does.
//!
//! Regenerating the golden after a deliberate long-only behaviour change is a decision to make in review, not a way
//! to make this test pass.

mod common;

use std::collections::BTreeMap;
use std::fmt::Write as _;

use broker_adapters::alpaca::{self, AssetTable};
use broker_adapters::kraken::pairs::PairTable;
use common::*;
use rebalancer_core::dec_math::{add, div_floor, mul, neg, sub};
use rebalancer_core::guard::{AccountView, Position, PricePoint};
use rebalancer_core::planner::{OrderPlanner, PlanConfig, SleeveTarget, TargetWeight};
use rebalancer_core::venue::{AlpacaRules, KrakenRules, VenueRuleBook};
use rebalancer_core::Dec;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};

const ETFS: [&str; 5] = ["SPY", "EFA", "IEF", "DBC", "VNQ"];
const ALL: [&str; 7] = ["SPY", "EFA", "IEF", "DBC", "VNQ", "BTC/USD", "ETH/USD"];
const CASES: u64 = 1500;
const GOLDEN: &str = include_str!("golden/long_only_plans.txt");
const GOLDEN_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/long_only_plans.txt");

fn price_for(rng: &mut SplitMix64, symbol: &str) -> Dec {
    let (lo, hi) = match symbol {
        "SPY" => (300, 600),
        "EFA" => (60, 100),
        "IEF" => (80, 110),
        "DBC" => (20, 30),
        "VNQ" => (70, 110),
        "BTC/USD" => (20_000, 100_000),
        "ETH/USD" => (1_000, 5_000),
        _ => (300, 500),
    };
    let whole = rng.range(lo, hi);
    let cents = rng.range(0, 99);
    d(&format!("{whole}.{cents:02}"))
}

fn pick_dec(rng: &mut SplitMix64, items: &[&str]) -> Dec {
    d(items[rng.range(0, items.len() as u64 - 1) as usize])
}

fn weight(rng: &mut SplitMix64, valid_only: bool, crypto: bool) -> Dec {
    if !valid_only && rng.chance(4) {
        return pick_dec(rng, &["-0.1", "1.5", "2", "0.6"]);
    }
    if crypto {
        pick_dec(rng, &["0", "0", "0.25", "0.5", "0.5"])
    } else {
        pick_dec(rng, &["0", "0", "0", "0.1", "0.2", "0.2"])
    }
}

fn canonical(result: &Result<rebalancer_core::planner::OrderPlan, rebalancer_core::planner::PlanError>) -> String {
    match result {
        Err(e) => format!("ERR {e:?}"),
        Ok(p) => {
            let mut s = String::new();
            write!(
                s,
                "digest={}|acct={}|sched={}|eq={}|cb={}|rs={}\norders={:?}\ndenied={:?}\nskipped={:?}\nlines={:?}",
                p.inputs_digest, p.account_id, p.scheduled_for, p.equity, p.capital_base, p.risk_scale, p.orders, p.denied, p.skipped, p.lines
            )
            .unwrap();
            s
        }
    }
}

fn run_case(seed: u64) -> (String, String) {
    let mut rng = SplitMix64(seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) ^ 0x1234_5678);
    let max_gross = *rng.pick(&[0.6, 0.8, 1.0, 1.0]);
    let positions_cap: Vec<f64> = [0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 1.0].into_iter().filter(|p| *p <= max_gross).collect();
    let classes: Vec<f64> = [0.2, 0.3, 0.4, 0.6, 1.0].into_iter().filter(|p| *p <= max_gross).collect();
    let max_position = *rng.pick(&positions_cap);
    let crypto_cap = *rng.pick(&classes);
    let reserve = *rng.pick(&[0.0, 0.01, 0.05, 0.1, 0.2]);
    let notional = *rng.pick(&[300.0, 1000.0, 1500.0, 5000.0]);
    let orders = *rng.pick(&[1u64, 2, 3, 5, 8, 20, 50]);
    let turnover = *rng.pick(&[0.1, 0.3, 0.5, 1.0, 3.0]);
    let shorting = rng.chance(40);
    let policy = policy_with(|m: &mut Value| {
        m["universe"]["instrument_allow"] = json!(ALL);
        m["universe"]["shorting"] = json!(shorting);
        m["exposure"]["max_position"] = json!(max_position);
        m["exposure"]["max_asset_class"] = json!({"crypto_spot": crypto_cap});
        m["universe"]["leverage_max_gross"] = json!(max_gross.max(1.0));
        m["exposure"]["max_gross"] = json!(max_gross);
        m["exposure"]["max_net"] = json!(max_gross);
        m["exposure"]["max_order_notional"]["amount"] = json!(format!("{notional:.2}"));
        m["exposure"]["max_orders_per_day"] = json!(orders);
        m["exposure"]["max_turnover_per_day"] = json!(turnover);
        m["capital"]["min_cash_reserve"] = json!(reserve);
    });

    let equity = rng.range(1_000, 20_000);
    let mut prices = BTreeMap::new();
    for s in ALL.iter().chain(["QQQ"].iter()) {
        prices.insert(s.to_string(), PricePoint { price: price_for(&mut rng, s), as_of: now() });
    }
    let mut positions = Vec::new();
    let mut invested = Dec::ZERO;
    for s in ALL.iter().chain(["QQQ"].iter()) {
        if !rng.chance(45) {
            continue;
        }
        let px = prices[*s].price;
        let frac = rng.range(1, 100);
        let value = mul(d(&equity.min(5_000).to_string()), d(&format!("0.{frac:03}"))).unwrap();
        let mut qty = div_floor(value, px, 6).unwrap();
        if qty.is_zero() {
            continue;
        }
        if rng.chance(8) {
            qty = neg(qty).unwrap();
        }
        let mv = mul(qty, px).unwrap();
        invested = add(invested, mv).unwrap();
        let (venue, class) = venue_and_class(s);
        positions.push(Position { symbol: s.to_string(), venue: venue.into(), asset_class: class.into(), quantity: qty, market_value: mv });
    }
    let equity_dec = d(&equity.to_string());
    let mut cash = sub(equity_dec, invested).unwrap();
    if cash.is_negative() && !rng.chance(10) {
        cash = Dec::ZERO;
    }
    let account = AccountView {
        account_id: format!("acct-{seed}"),
        ccy: "USD".into(),
        equity: equity_dec,
        cash,
        positions,
        halted: rng.chance(6),
        now: now(),
    };
    if rng.chance(6) {
        prices.get_mut("SPY").unwrap().as_of = now() - chrono::Duration::seconds(400);
    }
    if rng.chance(4) {
        prices.remove("DBC");
    }

    let etf_share = pick_dec(&mut rng, &["0.2", "0.4", "0.5", "0.6", "1", "0.3"]);
    let crypto_share = pick_dec(&mut rng, &["0", "0.2", "0.4", "0.5", "0.7"]);
    let valid_only = rng.chance(75);
    let mut targets = vec![SleeveTarget {
        sleeve: "etf".into(),
        share: etf_share,
        venue: "alpaca".into(),
        asset_class: "us_etf".into(),
        weights: ETFS.iter().map(|s| TargetWeight { symbol: s.to_string(), weight: weight(&mut rng, valid_only, false) }).collect(),
    }];
    if rng.chance(2) {
        let dup = TargetWeight { symbol: "spy".into(), weight: d("0.05") };
        targets[0].weights.push(dup);
    }
    if !crypto_share.is_zero() {
        targets.push(SleeveTarget {
            sleeve: "crypto".into(),
            share: crypto_share,
            venue: "kraken".into(),
            asset_class: "crypto_spot".into(),
            weights: vec![
                TargetWeight { symbol: "BTC/USD".into(), weight: weight(&mut rng, valid_only, true) },
                TargetWeight { symbol: "ETH/USD".into(), weight: weight(&mut rng, valid_only, true) },
            ],
        });
    }
    let risk_scale = if rng.chance(3) { pick_dec(&mut rng, &["0", "1.5"]) } else { pick_dec(&mut rng, &["1", "0.75", "0.5", "0.25", "0.1"]) };
    let mut cfg = PlanConfig::new(
        at("2026-10-01T14:00:00Z"),
        risk_scale,
        pick_dec(&mut rng, &["0", "5", "25"]),
        pick_dec(&mut rng, &["0", "0.02", "0.1"]),
        pick_dec(&mut rng, &["0", "0.001", "0.0026", "0.01"]),
    );
    cfg.credit_sell_proceeds = rng.chance(70);
    if rng.chance(20) {
        cfg.day.orders_today = 2;
        cfg.day.turnover_today = d("500");
    }

    let assets = if rng.chance(30) {
        let rows: Vec<Value> = ETFS.iter().map(|s| json!({"symbol": s, "tradable": true, "fractionable": false, "status": "active"})).collect();
        AssetTable::from_assets_json(&Value::Array(rows).to_string()).unwrap()
    } else {
        AssetTable::builtin()
    };
    let pairs = PairTable::builtin();
    let opts = alpaca::PrepareOptions { allow_extended_hours: false, min_notional: d("1"), own_tag_prefix: None, refuse_builtin_assets: false };
    let k = KrakenRules { pairs: &pairs };
    let a = AlpacaRules { assets: &assets, options: &opts };
    let book = VenueRuleBook::new().with("kraken", &k).with("alpaca", &a);
    let result = OrderPlanner::plan(&targets, &account, &prices, &book, &policy, &cfg);
    let text = canonical(&result);
    let summary = match &result {
        Ok(p) => format!("orders={} denied={} skipped={}", p.orders.len(), p.denied.len(), p.skipped.len()),
        Err(_) => "error".to_string(),
    };
    (hex::encode(Sha256::digest(text.as_bytes())), summary)
}

fn generate() -> String {
    let mut out = String::new();
    for seed in 0..CASES {
        let (hash, summary) = run_case(seed);
        writeln!(out, "{seed} {hash} {summary}").unwrap();
    }
    out
}

#[test]
fn long_only_plans_are_byte_for_byte_the_pre_extension_plans() {
    let actual = generate();
    if std::env::var("GOLDEN_UPDATE").as_deref() == Ok("1") {
        std::fs::create_dir_all(std::path::Path::new(GOLDEN_PATH).parent().unwrap()).unwrap();
        std::fs::write(GOLDEN_PATH, &actual).unwrap();
        return;
    }
    let expected: Vec<&str> = GOLDEN.lines().collect();
    let got: Vec<&str> = actual.lines().collect();
    assert_eq!(expected.len(), got.len(), "golden has {} cases, this run produced {}", expected.len(), got.len());
    for (e, g) in expected.iter().zip(&got) {
        assert_eq!(e, g, "long-only behaviour changed for case {}", e.split(' ').next().unwrap());
    }
    // The generator must reach both plans and refusals, or the equivalence proves little.
    let with_orders = got.iter().filter(|l| !l.ends_with("orders=0 denied=0 skipped=0") && !l.ends_with("error")).count();
    let errors = got.iter().filter(|l| l.ends_with("error")).count();
    assert!(with_orders > (CASES as usize) / 3, "too few cases with activity: {with_orders}");
    assert!(errors > 20, "too few refused cases: {errors}");
}
